### ISSUE TITLE
A question about throughput

### ISSUE THREAD

**Issue by SanmAIGO** [LMMMEng/TransXNet#12]
When I use the Train.py file in my project to train my dataset, I find that the training speed of TransXNet is much slower than models with similar parameter counts, such as PVT_V2, to the point where I believe my server is stuck. I encounter the same issue when using my own training script. Why is this happening? The data is fine because the timm library can train correctly.

**Comment by LMMMEng** [comment]
Sorry for the late response. Compared to PVTv2 with the same number of parameters, TransXNet is indeed slower due to its more complex architecture. However, it's worth noting that TransXNet can outperform PVTv2 with only half the number of parameters. As shown in Table 2 of the paper, TransXNet-S (26M) achieves better performance than PVTv2-b4 (62M). Therefore, it's worth considering using a smaller TransXNet model with fewer parameters.
